#!/bin/bash

PATH_ROOT=`dirname $0`

function run {
    node ${PATH_ROOT}/scripts/${1}
}

# Ensure the required version of Node.js is installed. If it isn't, try to
# install it automatically.
run utility/check-node
if [ $? -ne 0 ]; then
    run install-goals/node
    if [ $? -ne 0 ]; then
        exit
    fi

    run utility/check-node
    if [ $? -ne 0 ]; then
        echo "Default node command is not mapped to required version."
        exit
    fi
fi

# Install npm packages. See package.json.
npm install ${PATH_ROOT}

echo "Randar installed. <3"
