#!/bin/bash

PATH_ROOT=`dirname $0`
CMD_SYSTEM_INSTALL="sudo apt-get install"

function run {
    node ${PATH_ROOT}/scripts/${1} || return 1
    return 0
}

function isCommand {
    command -v ${1} > /dev/null 2>&1 || return 1
    return 0
}

# Creates a symlink if the node command is not available but nodejs is. Returns
# 0 if the node command was already available or is now available, 1 otherwise.
function symlinkNode {
    isCommand node || {
        isCommand nodejs || return 1
        PATH_USR_BINARY=`command -v nodejs | xargs dirname`
        ln -s ${PATH_USR_BINARY}/nodejs ${PATH_USR_BINARY}/node || return 1
    }

    return 0
}

# Basic dependencies.
${CMD_SYSTEM_INSTALL} make g++

# Ensure some version of Node.js is installed.
symlinkNode
isCommand node || {
    ${CMD_SYSTEM_INSTALL} nodejs-dev || exit
    symlinkNode || exit
}

# Ensure the required version of Node.js is installed. If it isn't, try to
# install it automatically.
run utility/check-node || {
    run install-goals/node || exit
    run utility/check-node || {
        echo "Default node command is not mapped to required version."
        exit
    }
}

# Install node-gyp globally.
sudo npm install -g node-gyp || exit

# Install npm packages. See package.json.
npm install ${PATH_ROOT}

echo "Randar installed. <3"
