#!/bin/bash
cat << "EOF"

     This software may not be used, distributed,
      reverse engineered, analyzed, or derived
  without the explicit permission of Alexander Litty.


                    Behold:


  ██████╗  █████╗ ███╗   ██╗██████╗  █████╗ ██████╗ 
  ██╔══██╗██╔══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
  ██████╔╝███████║██╔██╗ ██║██║  ██║███████║██████╔╝
  ██╔══██╗██╔══██║██║╚██╗██║██║  ██║██╔══██║██╔══██╗
  ██║  ██║██║  ██║██║ ╚████║██████╔╝██║  ██║██║  ██║
  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝


        The animated film production suite
                by Litty Studios


              www.littystudios.com
            San Francisco, California


      No soul dictates the potential of another.
    Surround yourself with nothing less than love
                forever and always.


      run/help ........ Shows this sappy inspiration.
      run/install ..... Installs the suite.
      run/uninstall ... Don't do this.
      run/build ....... Builds all modules.
      run/rebuild ..... Rebuilds all modules.
      run/test ........ Runs automated test suite.
      run/ui .......... Starts the user interface.

EOF
