#!/bin/bash
cat << "EOF"

     This software may not be used, distributed,
      reverse engineered, analyzed, or derived
  without the explicit permission of Alexander Litty.


                    Behold:


  ██████╗  █████╗ ███╗   ██╗██████╗  █████╗ ██████╗ 
  ██╔══██╗██╔══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
  ██████╔╝███████║██╔██╗ ██║██║  ██║███████║██████╔╝
  ██╔══██╗██╔══██║██║╚██╗██║██║  ██║██╔══██║██╔══██╗
  ██║  ██║██║  ██║██║ ╚████║██████╔╝██║  ██║██║  ██║
  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝


        The animated film production suite
                by Litty Studios


              www.littystudios.com
            San Francisco, California


      run/install ..... Installs the suite.
      run/uninstall ... Don't do this.
      run/build ....... Builds all modules.
      run/rebuild ..... Rebuilds all modules.

      run/test ........ Runs automated test suite.
      run/demo ........ Interactively runs a demo.
      run/ui .......... Starts the user interface.

      run/count ....... Count total lines of code.
      run/help ........ Shows this helpful text.

EOF
