#!/bin/bash
RANDAR_PATH=`dirname $0`
CMD_SYSTEM_INSTALL="sudo apt-get install"
CMD_NPM_INSTALL="npm install --loglevel http"

function run {
    node ${RANDAR_PATH}/scripts/${1} || return 1
    return 0
}

function isCommand {
    command -v ${1} > /dev/null 2>&1 || return 1
    return 0
}

# Creates a symlink if the node command is not available but nodejs is. Returns
# 0 if the node command was already available or is now available, 1 otherwise.
function symlinkNode {
    isCommand node || {
        isCommand nodejs || return 1
        PATH_USR_BINARY=`command -v nodejs | xargs dirname`
        sudo ln -s ${PATH_USR_BINARY}/nodejs ${PATH_USR_BINARY}/node || return 1
    }

    return 0
}

# System-level dependencies.
ENGINE_DEPENDENCIES="g++ libglew-dev libglm-dev libbullet-dev libpng-dev"
SWIG_DEPENDENCIES="pkg-config autoconf automake libtool libpcre++-dev bison"
${CMD_SYSTEM_INSTALL} ${ENGINE_DEPENDENCIES} ${SWIG_DEPENDENCIES} || exit

# Ensure some version of Node.js is installed.
symlinkNode
isCommand node || {
    ${CMD_SYSTEM_INSTALL} nodejs-dev || exit
    symlinkNode || exit
}

# Ensure the required version of Node.js is installed. If it isn't, try to
# install it automatically.
run utility/check-node || {
    run install-goals/node || exit
    run utility/check-node || {
        echo "Default node command is not mapped to required version."
        exit
    }
}

# Install global npm packages. This cannot be done via package.json.
isCommand node-gyp || {
    sudo ${CMD_NPM_INSTALL} -g node-gyp || exit
}

# Install non-global npm packages. See package.json.
${CMD_NPM_INSTALL} ${RANDAR_PATH} || exit

# Ensure SWIG is installed.
run utility/check-swig || {
    run install-goals/swig || exit
    run utility/check-swig || {
        echo "SWIG has been installed but executable is unavailable."
        exit
    }
}

# Perform a first-time build.
${RANDAR_PATH}/run/build || exit

# :)
cat << "EOF"

██████╗  █████╗ ███╗   ██╗██████╗  █████╗ ██████╗ 
██╔══██╗██╔══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
██████╔╝███████║██╔██╗ ██║██║  ██║███████║██████╔╝
██╔══██╗██╔══██║██║╚██╗██║██║  ██║██╔══██║██╔══██╗
██║  ██║██║  ██║██║ ╚████║██████╔╝██║  ██║██║  ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
                                                  
EOF
echo "Installed. <3 Go make something beautiful."
